### PR TITLE
Fix Next.js 8.1.0 compatibility

### LINKED ISSUE #11: config.externals is undefined in nextjs 8.1
Just upgraded to next.js version 8.1
execute `npm run dev`
Error is reported as config.externals is undefined.
`(node:11843) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Object.webpack (/Users/imsure/gavin-chan/Gitlab/imsure_web_fe/node_modules/next-plugin-transpile-modules/index.js:32:43)`

FYI: 
[https://github.com/zeit/next.js/pull/6983](https://github.com/zeit/next.js/pull/6983)

[https://github.com/zeit/next.js/issues/6946](https://github.com/zeit/next.js/issues/6946)

### PR DESCRIPTION
**Pull request by EyMaddis**
Fixes #11

Externals changed and can now be undefined.

### CODE REVIEW

**Comment by sjsyrek** [comment]
Any movement on this possible? 😄

**Comment by jamesgorrie** [comment]
Apologies for the wait, I will try to be more vigilant in merging requests.
Thanks @EyMaddis for the PR.

Now available in `v2.2.1`.

**Comment by sjsyrek** [comment]
@jamesgorrie Did you publish to npm?

**Comment by jamesgorrie** [comment]
@sjsyrek `v2.2.1`, previously was `v2.2.0`.

**Comment by sjsyrek** [comment]
Thank you!

**Pull request merged**
